name: Deploy Vite Plus site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Vite Plus
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
      - name: Setup pnpm & install dependencies
        run: |
          vp i -g pnpm
          vp install
      - name: Build with Vite Plus
        run: vp build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=delnegend --commit-dirty=true --branch=main
